const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");
const path = require('path');

module.exports = {
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  plugins: [
    new MonacoWebpackPlugin({
      languages: [
        "cpp",
        "csharp",
        "css",
        "go",
        "html",
        "java",
        "javascript",
        "mysql",
        "objective-c",
        "php",
        "python",
        "ruby",
        "shell",
        "sql",
        "swift",
        "typescript",
      ],
      features: [
        "wordHighlighter",
        "snippets",
        // "!accessibilityHelp",
        // "!anchorSelect",
        // "!bracketMatching",
        // "!caretOperations",
        // "!clipboard",
        // "!codeAction",
        // "!codelens",
        // "!colorDetector",
        // "!comment",
        // "!contextmenu",
        // "!coreCommands",
        // "!cursorUndo",
        // "!dnd",
        // "!find",
        // "!folding",
        // "!fontZoom",
        // "!format",
        // "!gotoError",
        // "!gotoLine",
        // "!gotoSymbol",
        // "!hover",
        // "!iPadShowKeyboard",
        // "!inPlaceReplace",
        // "!indentation",
        // "!inspectTokens",
        // "!linesOperations",
        // "!links",
        // "!multicursor",
        // "!onTypeRename",
        // "!parameterHints",
        // "!quickCommand",
        // "!quickHelp",
        // "!quickOutline",
        // "!referenceSearch",
        // "!rename",
        // "!smartSelect",
        // "!suggest",
        // "!toggleHighContrast",
        // "!toggleTabFocusMode",
        // "!transpose",
        // "!unusualLineTerminators",
        // "!viewportSemanticTokens",
        // "!wordOperations",
        // "!wordPartOperations",
      ],
    }),
  ],
};
